/* Generated by Yosys 0.33+6 (git sha1 41b34a193, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1694128612374/work=/usr/local/src/conda/yosys-0.33_7_g41b34a193 -fdebug-prefix-map=/home/ale/miniconda3/envs/digital=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

/* hdlname = "\\top" */
/* dynports =  1  */
/* top =  1  */
/* src = "top.v:1.1-60.10" */
module top(clk, rst, init, A, B, pp, done);
  /* src = "top.v:5.18-5.19" */
  input [3:0] A;
  wire [3:0] A;
  /* src = "top.v:6.18-6.19" */
  input [3:0] B;
  wire [3:0] B;
  /* hdlname = "acc_instance A" */
  /* src = "top.v:19.30-25.6|internal/acc.v:3.23-3.24" */
  wire [7:0] \acc_instance.A ;
  /* hdlname = "acc_instance add" */
  /* src = "top.v:19.30-25.6|internal/acc.v:4.11-4.14" */
  wire \acc_instance.add ;
  wire \acc_instance.add_TRELLIS_FF_Q_DI ;
  /* hdlname = "acc_instance clk" */
  /* src = "top.v:19.30-25.6|internal/acc.v:2.11-2.14" */
  wire \acc_instance.clk ;
  /* hdlname = "acc_instance pp" */
  /* src = "top.v:19.30-25.6|internal/acc.v:6.28-6.30" */
  wire [7:0] \acc_instance.pp ;
  /* force_downto = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:15.15-15.21|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:38.23-38.25" */
  /* unused_bits = "0 2 4 6 7" */
  wire [7:0] \acc_instance.pp_CCU2C_B0_COUT ;
  wire \acc_instance.pp_TRELLIS_FF_Q_1_LSR ;
  wire \acc_instance.pp_TRELLIS_FF_Q_2_LSR ;
  wire \acc_instance.pp_TRELLIS_FF_Q_3_LSR ;
  wire \acc_instance.pp_TRELLIS_FF_Q_4_LSR ;
  wire \acc_instance.pp_TRELLIS_FF_Q_5_LSR ;
  wire \acc_instance.pp_TRELLIS_FF_Q_6_LSR ;
  wire \acc_instance.pp_TRELLIS_FF_Q_7_LSR ;
  /* force_downto = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:15.15-15.21|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:34.26-34.27" */
  wire [7:0] \acc_instance.pp_TRELLIS_FF_Q_DI ;
  wire \acc_instance.pp_TRELLIS_FF_Q_LSR ;
  /* src = "top.v:14.24-14.27" */
  wire add;
  /* src = "top.v:2.11-2.14" */
  input clk;
  wire clk;
  /* hdlname = "cm_instance add" */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:14.14-14.17" */
  wire \cm_instance.add ;
  /* hdlname = "cm_instance clk" */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:5.9-5.12" */
  wire \cm_instance.clk ;
  /* hdlname = "cm_instance count" */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:24.13-24.18" */
  wire [2:0] \cm_instance.count ;
  wire \cm_instance.count_TRELLIS_FF_Q_CE ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \cm_instance.count_TRELLIS_FF_Q_CE_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \cm_instance.count_TRELLIS_FF_Q_CE_PFUMX_Z_BLUT ;
  /* hdlname = "cm_instance done" */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:11.14-11.18" */
  wire \cm_instance.done ;
  /* hdlname = "cm_instance init" */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:8.9-8.13" */
  wire \cm_instance.init ;
  /* hdlname = "cm_instance lsb_B" */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:7.9-7.14" */
  wire \cm_instance.lsb_B ;
  /* src = "top.v:32.28-38.6|internal/rsr.v:9.5-14.8" */
  wire \cm_instance.lsb_B_TRELLIS_FF_Q_DI ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* hdlname = "cm_instance next_count" */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:24.20-24.30" */
  wire [2:0] \cm_instance.next_count ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire \cm_instance.next_count_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire \cm_instance.next_count_PFUMX_Z_BLUT ;
  /* hdlname = "cm_instance rst" */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:6.9-6.12" */
  wire \cm_instance.rst ;
  /* hdlname = "cm_instance sh" */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:12.14-12.16" */
  wire \cm_instance.sh ;
  wire \cm_instance.sh_TRELLIS_FF_Q_DI ;
  /* onehot = 32'd1 */
  wire [4:0] \cm_instance.state ;
  wire \cm_instance.state_TRELLIS_FF_Q_1_DI ;
  wire \cm_instance.state_TRELLIS_FF_Q_DI ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.66-157.68" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.50-157.52" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.22-157.24" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.18-157.20" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.54-157.56" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.30-157.32" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.26-157.28" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.70-157.72" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.58-157.60" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.38-157.40" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.34-157.36" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.62-157.64" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.46-157.48" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:157.42-157.44" */
  wire \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* hdlname = "comp_instance B" */
  /* src = "top.v:27.29-30.6|internal/comp.v:2.21-2.22" */
  wire [3:0] \comp_instance.B ;
  /* src = "top.v:8.12-8.16" */
  output done;
  wire done;
  wire done_TRELLIS_FF_Q_DI;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.22-133.24" */
  wire done_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:133.18-133.20" */
  wire done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT;
  /* src = "top.v:4.11-4.15" */
  input init;
  wire init;
  /* hdlname = "lsr_instance clk" */
  /* src = "top.v:40.28-46.6|internal/lsr.v:2.9-2.12" */
  wire \lsr_instance.clk ;
  /* hdlname = "lsr_instance in_A" */
  /* src = "top.v:40.28-46.6|internal/lsr.v:3.20-3.24" */
  wire [3:0] \lsr_instance.in_A ;
  /* hdlname = "lsr_instance s_A" */
  /* src = "top.v:40.28-46.6|internal/lsr.v:6.25-6.28" */
  wire [3:0] \lsr_instance.s_A ;
  /* force_downto = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:15.15-15.21|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:63.22-63.23" */
  /* unused_bits = "1 3 5 7" */
  wire [7:0] \lsr_instance.s_A_CCU2C_A0_COUT ;
  /* src = "top.v:40.28-46.6|internal/lsr.v:8.1-17.7" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_1_DI ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* src = "top.v:40.28-46.6|internal/lsr.v:8.1-17.7" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_2_DI ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* src = "top.v:40.28-46.6|internal/lsr.v:8.1-17.7" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_3_DI ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* hdlname = "lsr_instance shift" */
  /* src = "top.v:40.28-46.6|internal/lsr.v:5.9-5.14" */
  wire \lsr_instance.shift ;
  /* src = "top.v:7.27-7.29" */
  output [7:0] pp;
  wire [7:0] pp;
  /* hdlname = "rsr_instance clk" */
  /* src = "top.v:32.28-38.6|internal/rsr.v:2.11-2.14" */
  wire \rsr_instance.clk ;
  /* hdlname = "rsr_instance in_B" */
  /* src = "top.v:32.28-38.6|internal/rsr.v:3.23-3.27" */
  wire [3:0] \rsr_instance.in_B ;
  /* hdlname = "rsr_instance s_B" */
  /* src = "top.v:32.28-38.6|internal/rsr.v:6.28-6.31" */
  wire [3:0] \rsr_instance.s_B ;
  /* src = "top.v:32.28-38.6|internal/rsr.v:9.5-14.8" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_1_DI ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* src = "top.v:32.28-38.6|internal/rsr.v:9.5-14.8" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_2_DI ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.34-141.36" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.22-141.24" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.18-141.20" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.38-141.40" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1 ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.30-141.32" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:141.26-141.28" */
  wire \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  wire \rsr_instance.s_B_TRELLIS_FF_Q_CE ;
  /* hdlname = "rsr_instance shift" */
  /* src = "top.v:32.28-38.6|internal/rsr.v:4.11-4.16" */
  wire \rsr_instance.shift ;
  /* src = "top.v:3.11-3.14" */
  input rst;
  wire rst;
  /* src = "top.v:14.10-14.15" */
  wire shift;
  /* src = "top.v:15.26-15.29" */
  wire [7:0] w_A;
  /* src = "top.v:16.24-16.27" */
  wire [3:0] w_B;
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_instance.add_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\acc_instance.add_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\acc_instance.add )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:15.15-15.21|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc_instance.pp_CCU2C_B0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc_instance.pp [6]),
    .B1(\acc_instance.pp [7]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\lsr_instance.s_A_CCU2C_A0_COUT [6]),
    .COUT(\acc_instance.pp_CCU2C_B0_COUT [7]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc_instance.pp_TRELLIS_FF_Q_DI [6]),
    .S1(\acc_instance.pp_TRELLIS_FF_Q_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:15.15-15.21|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc_instance.pp_CCU2C_B0_1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\acc_instance.pp [4]),
    .B1(\acc_instance.pp [5]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\lsr_instance.s_A_CCU2C_A0_COUT [4]),
    .COUT(\lsr_instance.s_A_CCU2C_A0_COUT [6]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc_instance.pp_TRELLIS_FF_Q_DI [4]),
    .S1(\acc_instance.pp_TRELLIS_FF_Q_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:11.1-16.4|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc_instance.pp_TRELLIS_FF_Q  (
    .CE(\acc_instance.add ),
    .CLK(clk),
    .DI(\acc_instance.pp_TRELLIS_FF_Q_DI [7]),
    .LSR(\acc_instance.pp_TRELLIS_FF_Q_LSR ),
    .Q(\acc_instance.pp [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:11.1-16.4|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc_instance.pp_TRELLIS_FF_Q_1  (
    .CE(\acc_instance.add ),
    .CLK(clk),
    .DI(\acc_instance.pp_TRELLIS_FF_Q_DI [6]),
    .LSR(\acc_instance.pp_TRELLIS_FF_Q_1_LSR ),
    .Q(\acc_instance.pp [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \acc_instance.pp_TRELLIS_FF_Q_1_LSR_LUT4_Z  (
    .A(\cm_instance.sh ),
    .B(done),
    .C(\cm_instance.state [3]),
    .D(\acc_instance.add ),
    .Z(\acc_instance.pp_TRELLIS_FF_Q_1_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:11.1-16.4|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc_instance.pp_TRELLIS_FF_Q_2  (
    .CE(\acc_instance.add ),
    .CLK(clk),
    .DI(\acc_instance.pp_TRELLIS_FF_Q_DI [5]),
    .LSR(\acc_instance.pp_TRELLIS_FF_Q_2_LSR ),
    .Q(\acc_instance.pp [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \acc_instance.pp_TRELLIS_FF_Q_2_LSR_LUT4_Z  (
    .A(\cm_instance.sh ),
    .B(done),
    .C(\cm_instance.state [3]),
    .D(\acc_instance.add ),
    .Z(\acc_instance.pp_TRELLIS_FF_Q_2_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:11.1-16.4|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc_instance.pp_TRELLIS_FF_Q_3  (
    .CE(\acc_instance.add ),
    .CLK(clk),
    .DI(\acc_instance.pp_TRELLIS_FF_Q_DI [4]),
    .LSR(\acc_instance.pp_TRELLIS_FF_Q_3_LSR ),
    .Q(\acc_instance.pp [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \acc_instance.pp_TRELLIS_FF_Q_3_LSR_LUT4_Z  (
    .A(\cm_instance.sh ),
    .B(done),
    .C(\cm_instance.state [3]),
    .D(\acc_instance.add ),
    .Z(\acc_instance.pp_TRELLIS_FF_Q_3_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:11.1-16.4|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc_instance.pp_TRELLIS_FF_Q_4  (
    .CE(\acc_instance.add ),
    .CLK(clk),
    .DI(\acc_instance.pp_TRELLIS_FF_Q_DI [3]),
    .LSR(\acc_instance.pp_TRELLIS_FF_Q_4_LSR ),
    .Q(\acc_instance.pp [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \acc_instance.pp_TRELLIS_FF_Q_4_LSR_LUT4_Z  (
    .A(\cm_instance.sh ),
    .B(done),
    .C(\cm_instance.state [3]),
    .D(\acc_instance.add ),
    .Z(\acc_instance.pp_TRELLIS_FF_Q_4_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:11.1-16.4|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc_instance.pp_TRELLIS_FF_Q_5  (
    .CE(\acc_instance.add ),
    .CLK(clk),
    .DI(\acc_instance.pp_TRELLIS_FF_Q_DI [2]),
    .LSR(\acc_instance.pp_TRELLIS_FF_Q_5_LSR ),
    .Q(\acc_instance.pp [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \acc_instance.pp_TRELLIS_FF_Q_5_LSR_LUT4_Z  (
    .A(\cm_instance.sh ),
    .B(done),
    .C(\cm_instance.state [3]),
    .D(\acc_instance.add ),
    .Z(\acc_instance.pp_TRELLIS_FF_Q_5_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:11.1-16.4|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc_instance.pp_TRELLIS_FF_Q_6  (
    .CE(\acc_instance.add ),
    .CLK(clk),
    .DI(\acc_instance.pp_TRELLIS_FF_Q_DI [1]),
    .LSR(\acc_instance.pp_TRELLIS_FF_Q_6_LSR ),
    .Q(\acc_instance.pp [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \acc_instance.pp_TRELLIS_FF_Q_6_LSR_LUT4_Z  (
    .A(\cm_instance.sh ),
    .B(done),
    .C(\cm_instance.state [3]),
    .D(\acc_instance.add ),
    .Z(\acc_instance.pp_TRELLIS_FF_Q_6_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:11.1-16.4|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc_instance.pp_TRELLIS_FF_Q_7  (
    .CE(\acc_instance.add ),
    .CLK(clk),
    .DI(\acc_instance.pp_TRELLIS_FF_Q_DI [0]),
    .LSR(\acc_instance.pp_TRELLIS_FF_Q_7_LSR ),
    .Q(\acc_instance.pp [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \acc_instance.pp_TRELLIS_FF_Q_7_LSR_LUT4_Z  (
    .A(\cm_instance.sh ),
    .B(done),
    .C(\cm_instance.state [3]),
    .D(\acc_instance.add ),
    .Z(\acc_instance.pp_TRELLIS_FF_Q_7_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \acc_instance.pp_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(\cm_instance.sh ),
    .B(done),
    .C(\cm_instance.state [3]),
    .D(\acc_instance.add ),
    .Z(\acc_instance.pp_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:26.3-34.6|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cm_instance.count_TRELLIS_FF_Q  (
    .CE(\cm_instance.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\cm_instance.next_count [2]),
    .LSR(rst),
    .Q(\cm_instance.count [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:26.3-34.6|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cm_instance.count_TRELLIS_FF_Q_1  (
    .CE(\cm_instance.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\cm_instance.next_count [1]),
    .LSR(rst),
    .Q(\cm_instance.count [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:48.18-58.6|internal/control_mult.v:26.3-34.6|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \cm_instance.count_TRELLIS_FF_Q_2  (
    .CE(\cm_instance.count_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\cm_instance.next_count [0]),
    .LSR(rst),
    .Q(\cm_instance.count [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \cm_instance.count_TRELLIS_FF_Q_CE_PFUMX_Z  (
    .ALUT(\cm_instance.count_TRELLIS_FF_Q_CE_PFUMX_Z_ALUT ),
    .BLUT(\cm_instance.count_TRELLIS_FF_Q_CE_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\cm_instance.count_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \cm_instance.count_TRELLIS_FF_Q_CE_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\cm_instance.count_TRELLIS_FF_Q_CE_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h000b)
  ) \cm_instance.count_TRELLIS_FF_Q_CE_PFUMX_Z_BLUT_LUT4_Z  (
    .A(init),
    .B(\cm_instance.state [0]),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\cm_instance.count_TRELLIS_FF_Q_CE_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h00f4)
  ) \cm_instance.lsb_B_LUT4_A  (
    .A(\cm_instance.lsb_B ),
    .B(\cm_instance.state [3]),
    .C(\acc_instance.add ),
    .D(rst),
    .Z(\cm_instance.sh_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \cm_instance.lsb_B_LUT4_C  (
    .A(1'h0),
    .B(rst),
    .C(\cm_instance.lsb_B ),
    .D(\cm_instance.state [3]),
    .Z(\acc_instance.add_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:32.28-38.6|internal/rsr.v:9.5-14.8|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \cm_instance.lsb_B_TRELLIS_FF_Q  (
    .CE(\rsr_instance.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\cm_instance.lsb_B_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\cm_instance.lsb_B )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z  (
    .D0(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0 ),
    .D1(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1 ),
    .SD(\rsr_instance.s_B [1]),
    .Z(\cm_instance.lsb_B_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(B[0]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'hfffe)
  ) \cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(B[0]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\cm_instance.lsb_B_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc300)
  ) \cm_instance.next_count_LUT4_Z  (
    .A(1'h0),
    .B(\cm_instance.count [0]),
    .C(\cm_instance.count [1]),
    .D(\cm_instance.sh ),
    .Z(\cm_instance.next_count [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) \cm_instance.next_count_LUT4_Z_1  (
    .A(1'h0),
    .B(1'h0),
    .C(\cm_instance.count [0]),
    .D(\cm_instance.sh ),
    .Z(\cm_instance.next_count [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX \cm_instance.next_count_PFUMX_Z  (
    .ALUT(\cm_instance.next_count_PFUMX_Z_ALUT ),
    .BLUT(\cm_instance.next_count_PFUMX_Z_BLUT ),
    .C0(\cm_instance.sh ),
    .Z(\cm_instance.next_count [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hfeab)
  ) \cm_instance.next_count_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\cm_instance.state [0]),
    .B(\cm_instance.count [0]),
    .C(\cm_instance.count [1]),
    .D(\cm_instance.count [2]),
    .Z(\cm_instance.next_count_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) \cm_instance.next_count_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\cm_instance.state [0]),
    .Z(\cm_instance.next_count_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \cm_instance.sh_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\cm_instance.sh_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\cm_instance.sh )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \cm_instance.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\cm_instance.state_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\cm_instance.state [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \cm_instance.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\cm_instance.state_TRELLIS_FF_Q_1_DI ),
    .LSR(1'h0),
    .Q(\cm_instance.state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfff4)
  ) \cm_instance.state_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(init),
    .B(\cm_instance.state [0]),
    .C(rst),
    .D(done),
    .Z(\cm_instance.state_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:184.21-184.63" */
  L6MUX21 \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z  (
    .D0(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0 ),
    .D1(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1 ),
    .SD(rst),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:182.21-182.64" */
  L6MUX21 \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z  (
    .D0(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0 ),
    .D1(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1 ),
    .SD(\cm_instance.sh ),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:178.19-178.65" */
  PFUMX \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\cm_instance.count [2]),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:160.39-161.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\cm_instance.state [0]),
    .D(init),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:158.39-159.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\cm_instance.state [0]),
    .D(init),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:179.19-179.65" */
  PFUMX \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\cm_instance.count [2]),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:165.39-166.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:163.39-164.56" */
  LUT4 #(
    .INIT(16'hffd5)
  ) \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(\cm_instance.count [0]),
    .B(\cm_instance.state [0]),
    .C(init),
    .D(\cm_instance.count [1]),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:183.21-183.64" */
  L6MUX21 \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z  (
    .D0(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0 ),
    .D1(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1 ),
    .SD(\cm_instance.sh ),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:180.19-180.65" */
  PFUMX \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\cm_instance.count [2]),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:170.39-171.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:168.39-169.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:181.19-181.65" */
  PFUMX \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\cm_instance.count [2]),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:175.41-176.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:173.41-174.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\cm_instance.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) done_TRELLIS_FF_Q (
    .CLK(clk),
    .DI(done_TRELLIS_FF_Q_DI),
    .LSR(1'h0),
    .Q(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:138.19-138.63" */
  PFUMX done_TRELLIS_FF_Q_DI_PFUMX_Z (
    .ALUT(done_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT),
    .BLUT(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT),
    .C0(\cm_instance.count [0]),
    .Z(done_TRELLIS_FF_Q_DI)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0100)
  ) done_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT_LUT4_Z (
    .A(\cm_instance.count [1]),
    .B(\cm_instance.count [2]),
    .C(rst),
    .D(\cm_instance.sh ),
    .Z(done_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:15.15-15.21|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lsr_instance.s_A_CCU2C_A0  (
    .A0(\lsr_instance.s_A [2]),
    .A1(\lsr_instance.s_A [3]),
    .B0(\acc_instance.pp [2]),
    .B1(\acc_instance.pp [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\lsr_instance.s_A_CCU2C_A0_COUT [2]),
    .COUT(\lsr_instance.s_A_CCU2C_A0_COUT [4]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc_instance.pp_TRELLIS_FF_Q_DI [2]),
    .S1(\acc_instance.pp_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:19.30-25.6|internal/acc.v:15.15-15.21|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/arith_map.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lsr_instance.s_A_CCU2C_A0_1  (
    .A0(\lsr_instance.s_A [0]),
    .A1(\lsr_instance.s_A [1]),
    .B0(\acc_instance.pp [0]),
    .B1(\acc_instance.pp [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\lsr_instance.s_A_CCU2C_A0_COUT [2]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc_instance.pp_TRELLIS_FF_Q_DI [0]),
    .S1(\acc_instance.pp_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:40.28-46.6|internal/lsr.v:8.1-17.7|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lsr_instance.s_A_TRELLIS_FF_Q  (
    .CE(\rsr_instance.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A[0]),
    .LSR(\cm_instance.sh ),
    .Q(\lsr_instance.s_A [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:40.28-46.6|internal/lsr.v:8.1-17.7|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr_instance.s_A_TRELLIS_FF_Q_1  (
    .CE(\rsr_instance.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI ),
    .LSR(1'h0),
    .Q(\lsr_instance.s_A [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z  (
    .D0(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0 ),
    .D1(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1 ),
    .SD(\lsr_instance.s_A [2]),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(A[3]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'hfffe)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(A[3]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:40.28-46.6|internal/lsr.v:8.1-17.7|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr_instance.s_A_TRELLIS_FF_Q_2  (
    .CE(\rsr_instance.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI ),
    .LSR(1'h0),
    .Q(\lsr_instance.s_A [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z  (
    .D0(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0 ),
    .D1(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1 ),
    .SD(\lsr_instance.s_A [1]),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(A[2]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'hfffe)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(A[2]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:40.28-46.6|internal/lsr.v:8.1-17.7|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lsr_instance.s_A_TRELLIS_FF_Q_3  (
    .CE(\rsr_instance.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI ),
    .LSR(1'h0),
    .Q(\lsr_instance.s_A [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z  (
    .D0(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0 ),
    .D1(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1 ),
    .SD(\lsr_instance.s_A [0]),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(A[1]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'hfffe)
  ) \lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(A[1]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\lsr_instance.s_A_TRELLIS_FF_Q_3_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:32.28-38.6|internal/rsr.v:9.5-14.8|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr_instance.s_B_TRELLIS_FF_Q  (
    .CE(\rsr_instance.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(B[3]),
    .LSR(\cm_instance.sh ),
    .Q(\rsr_instance.s_B [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:32.28-38.6|internal/rsr.v:9.5-14.8|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr_instance.s_B_TRELLIS_FF_Q_1  (
    .CE(\rsr_instance.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI ),
    .LSR(1'h0),
    .Q(\rsr_instance.s_B [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z  (
    .D0(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0 ),
    .D1(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1 ),
    .SD(\rsr_instance.s_B [3]),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(B[2]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'hfffe)
  ) \rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(B[2]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_1_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "top.v:32.28-38.6|internal/rsr.v:9.5-14.8|/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr_instance.s_B_TRELLIS_FF_Q_2  (
    .CE(\rsr_instance.s_B_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI ),
    .LSR(1'h0),
    .Q(\rsr_instance.s_B [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:154.21-154.62" */
  L6MUX21 \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z  (
    .D0(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0 ),
    .D1(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1 ),
    .SD(\rsr_instance.s_B [2]),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:152.19-152.65" */
  PFUMX \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:144.39-145.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:142.39-143.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(B[1]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:153.19-153.65" */
  PFUMX \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\acc_instance.add ),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:149.39-150.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:147.39-148.56" */
  LUT4 #(
    .INIT(16'hfffe)
  ) \rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(B[1]),
    .B(\cm_instance.sh ),
    .C(done),
    .D(\cm_instance.state [3]),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_2_DI_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/ale/miniconda3/envs/digital/bin/../share/yosys/ecp5/cells_map.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hff01)
  ) \rsr_instance.s_B_TRELLIS_FF_Q_CE_LUT4_Z  (
    .A(\cm_instance.state [3]),
    .B(\acc_instance.add ),
    .C(done),
    .D(\cm_instance.sh ),
    .Z(\rsr_instance.s_B_TRELLIS_FF_Q_CE )
  );
  assign \lsr_instance.s_A_CCU2C_A0_COUT [0] = 1'h0;
  assign \acc_instance.pp_CCU2C_B0_COUT [6:0] = \lsr_instance.s_A_CCU2C_A0_COUT [7:1];
  assign \acc_instance.A  = { 4'h0, \lsr_instance.s_A  };
  assign \acc_instance.clk  = clk;
  assign add = \acc_instance.add ;
  assign \cm_instance.add  = \acc_instance.add ;
  assign \cm_instance.clk  = clk;
  assign \cm_instance.done  = done;
  assign \cm_instance.init  = init;
  assign \cm_instance.rst  = rst;
  assign { \cm_instance.state [4], \cm_instance.state [2:1] } = { \acc_instance.add , \cm_instance.sh , done };
  assign \comp_instance.B  = { \rsr_instance.s_B [3:1], \cm_instance.lsb_B  };
  assign \lsr_instance.clk  = clk;
  assign \lsr_instance.in_A  = A;
  assign \lsr_instance.shift  = \cm_instance.sh ;
  assign pp = \acc_instance.pp ;
  assign \rsr_instance.clk  = clk;
  assign \rsr_instance.in_B  = B;
  assign \rsr_instance.s_B [0] = \cm_instance.lsb_B ;
  assign \rsr_instance.shift  = \cm_instance.sh ;
  assign shift = \cm_instance.sh ;
  assign w_A = { 4'h0, \lsr_instance.s_A  };
  assign w_B = { \rsr_instance.s_B [3:1], \cm_instance.lsb_B  };
endmodule
